name: CI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3
      timeout-minutes: 50
    - name: Upload Kernel
      uses: actions/upload-artifact@v4
      with:
        name: Image.gz
        path: ~/kernel-4.19/out/arch/arm64/boot/Image.gz

    - name: Upload kernel 2
      uses: actions/upload-artifact@v4
      with:
        name: Image
        path: ~/kernel-4.19/out/arch/arm64/boot/Image
