name: CI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false
        
jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Maximize build space
      uses: easimon/maximize-build-space@master
      with:
        root-reserve-mb: 512
        swap-size-mb: 1024
        remove-dotnet: 'true'
        remove-android: 'true'
        remove-haskell: 'true'
        remove-codeql: 'true'
        remove-docker-images: 'true'
    - name: Setup repository
      uses: actions/checkout@v3
    - name: Build
      run: |
          echo "Free space:"
          df -h

    - name: Make MACOS SDK
      run: |
         pip install gdown
         git clone --depth 1 https://github.com/tpoechtrager/osxcross.git
         cd osxcross
         sudo apt install lzma-dev libxml2-dev -y
         wget https://github.com/OPTIMALGLADIUS/Android-kernel-compile/actions/runs/10904332984/artifacts/1942921587
         https://github.com/OPTIMALGLADIUS/Android-kernel-compile/actions/runs/10904332984/artifacts/1942921334
         cp MacOSX15.sdk.tar.xz tarballs
         cp MacOSX15.0.sdk.tar.xz tarballs
         SDK_VERSION=15.0 ./build.sh
      
    - name: Setup tmate session
      uses: mxschmitt/action-tmate@v3

    - uses: actions/upload-artifact@v4 
      with:
        name: MacOSX15.sdk.tar.xz
        path: /home/runner/work/Android-kernel-compile/Android-kernel-compile/osxcross/MacOSX15.sdk.tar.xz

    - uses: actions/upload-artifact@v4
      with:
        name: MacOSX15.0.sdk.tar.xz
        path: /home/runner/work/Android-kernel-compile/Android-kernel-compile/osxcross/MacOSX15.0.sdk.tar.xz

