name: compile
on:
 workflow_dispatch:
   
jobs:
 bash-script:
  runs-on: ubuntu-latest

  steps:
   - name: Checkout
     uses: actions/checkout@v2

   - name: Run Script
     run: bash script.sh

   - name: Upload Kernel
     uses: actions/upload-artifact@v4
     with:
       name: Image.gz
       path: ~/kernel-4.19/out/arch/arm64/boot/Image.gz

   - name: Upload kernel 2
     uses: actions/upload-artifact@v4
     with:
       name: Image
       path: ~/kernel-4.19/out/arch/arm64/boot/Image
