name: GUI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with ngrock debugging enabled'
        required: false
        default: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1

      - name: Reverse RDP
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
             ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
             password: "OPTIMAL" # You can also put the password in secrets as you wish.
             foreground: true
