name: GUI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Test background
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
             ngrok-token: ${{ secrets.NGROK_AUTH_TOKEN }}
             password: "OPTIMAL" # You can also put the password in secrets as you wish.
             #foreground: false
