name: GUI
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: microsoft/setup-msbuild@v1.1

      - name: Test background
        uses: NyaMisty/reverse-rdp-windows-github-actions-ng@master
        with:
             ngrok-token: "2Bqk1U6wPLkHodGx1yFFwlPkjEJ_y3dVembe4myRbXLzBdvE"
             password: "OPTIMAL" # You can also put the password in secrets as you wish.
             #foreground: false
