name: MacOS
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true
jobs:
  build:
    runs-on: macos-latest
    steps:
     
      - uses: actions/checkout@v2

      - name: Build GCC
        run: |
            bash
            brew install binutils
            brew install texinfo
            xcode-select --install
            sudo cp -rf /opt/homebrew/include /usr/local/include
            sudo cp -rf /opt/homebrew/lib /usr/local/lib
            sudo cp -rf /opt/homebrew/bin /usr/local/bin
            git clone https://github.com/gcc-mirror/gcc.git --depth 1
            cd gcc
            mkdir build
            mkdir output
            cd build
            ../configure --target=aarch64-linux-gnu --prefix=$PWD/../output
      
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3

