name: Windows
on:
  workflow_dispatch:
    inputs:
      debug_enabled:
        type: boolean
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: true
jobs:
  build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
      - uses: microsoft/setup-msbuild@v1.1

      - name: Setup Ninja
        uses: seanmiddleditch/gha-setup-ninja@master
      
      - name: Download FBX SDK
        run: |
          pip install gdown
          gdown https://drive.google.com/uc?id=1X1BFi9NoELYfuFyTR8bXXgUvauVszvGG
          md fbx
          cd fbx
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_win.exe" -OutFile "fbxsdk.exe"
          Start-Process -FilePath "fbxsdk.exe" /S -Wait
          Invoke-WebRequest "https://damassets.autodesk.net/content/dam/autodesk/www/adn/fbx/2020-2-1/fbx202021_fbxsdk_vs2019_pdbs.exe" -OutFile "fbxpdb.exe"
          Start-Process -FilePath "fbxpdb.exe" /S -Wait
          cd ..

      - name: Clone
        run: |
             git clone https://github.com/aelurum/AssetStudio.git
             cd AssetStudio/AssetStudioFBXNative
             md build

      - name: Build .Net8
        run: |
            cd AssetStudio/AssetStudioFBXNative
            msbuild AssetStudioFBXNative.vcxproj /p:Configuration=Release /p:TargetFramework=net8.0-windows /p:RuntimeIdentifier=linux-arm64
       
      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
